Touchbar add
juvirez/yandex-music-app pull request #67
Opened 2021-03-07 22:41 UTC by neonrostov

Добавлен TouchBar в приложение
– like
– dislike
– title track
– play/pause
– prev/next track

2021-03-23 18:48 UTC, juvirez requested changes
Спасибо за PR!

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +  label: '️❤️',
Эмоджи в качестве иконок смотрятся как-то не очень. Может воспользуемся иконками из самой яндекс музыки? `TouchBarButton` поддерживает иконки.

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +  label: '️❤️',
Ну и было бы круто если бы иконки были в стиле системных — не цветные.
Красный цвет можно добавить лишь для `likeButton`, когда трек находится в статусе `liked`.

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +const dislikeButton = new TouchBarButton({
Проблема тачбара в том, что все постоянно промахиваются по кнопкам. А тут по соседству с кнопкой like, кнопка dislike. Причём undislike очень проблематично сделать, потому что песня сразу же скипается.
Поэтому, предлагаю dislike вообще не добавлять на тачбар.

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +  accessibilityLabel: 'Button looking like a label',
Думаю, лучше не добавлять такой `accessibilityLabel`. Смысла от него нет.

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +const playButton = new TouchBarButton({
Кнопку play логичнее расположить между prev / next.
А можно сделать так же как отображает макось с разделителями между кнопками?
![image](https://user-images.githubusercontent.com/1862143/112200522-c1076580-8c28-11eb-84b4-7e4cbb42b97c.png)

2021-03-23 18:48 UTC, juvirez commented on src/main/features/touchbar.js
> +  track.disliked = track.disliked ?? undefined;
Не совсем понял зачем это?
Если нужен undefined вместо null — давай сделаем это при присвоении к `trackDislike`.

2022-02-01 17:00 UTC, jag-k commented on src/main/features/touchbar.js
> +const dislikeButton = new TouchBarButton({
Думаю, при нажатии на dislike можно сделать отдельное подтверждение в том же TouchBar с примерно таким содержанием:

```
<Text content="Вы уверены, что хотите дизлайкнуть трек?"> | <wrap-space> | <Button bg="secondary" text="Отмена"> <Button bg="red" text="Да"> | <wrap-space>
```

Надеюсь, понятно объяснил, как это может выглядеть)

2022-05-30 20:31 UTC, juvirez approved these changes

2022-05-30 20:39 UTC, merged